apiVersion: apps/v1
kind: Deployment
metadata:
    name: python-test

spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
      metadata:
        labels:
          name: app-flask
          app: flask
      spec:
        containers:
          - name: python-test
            image: vinney55/ssysdevops2021:ssys
            ports:
              - containerPort: 8080