apiVersion: v1
kind: Service
metadata:
  name: service-flask
spec:
  type: LoadBalancer 
  ports:
   -  protocol: TCP
      port : 8080
      targetPort: 8080
      nodePort: 30000
      
  selector: 
    name: app-flask